---
title: "Short Writing Assignment 2: Quantitative Immigration Data Analysis - Answer Sheet"
output:
  pdf_document:
    df_print: paged
---


```{r}
# Uploading packages
library(tidyverse)
```

```{r}
# Uploading dataset
sea <- read.csv("sea.csv")
```

# Section 1 (10 points)

## a.  

#### Code:

```{r}

```

```{r}

```

```{r}

```

> **Answer:**

```{r}

```

## b. 

#### Code:

```{r}

```

> **Answer:**

```{r}

```


## c.  

#### Code:

```{r}

```

> **Answer:**

```{r}

```

## d.

#### Code:

```{r}

```

```{r}

```

> **Answer:**

```{r}

```

## e.  

> **Answer:**

```{r}

```

## f.  

> **Answer:**

```{r}

```

## g.  

> **Answer:**

```{r}

```

## h. 

#### Code:

```{r}

```

> **Answer:**

```{r}

```


## i.  

> **Answer:**

```{r}

```

# EXTRA CREDIT (3 points)

## j

#### Code:

```{r}

```

> **Answer:**

```{r}

```

## k.

#### Code:

```{r}

```

> **Answer:**

```{r}

```

## l. 

#### Code:

```{r}

```

> **Answer:**

```{r}

```



